"""The exact mutually exclusive taxonomy supplied to the LLM."""
TAXONOMY = {
    "stock_market": "Public equity investing, stock trading, ETFs, options, stock analysis, company valuation, portfolio management, and WallStreetBets-style investing. Discussions about general stock market investing.",
    "non_stock_investing": "Investing outside public equities or cryptocurrencies, including bonds, fixed income, commodities, precious metals, private equity, venture capital, collectibles, alternative investments, real estate investing, rental properties, house flipping, REITs.",
    "crypto": "Cryptocurrencies, blockchain, NFTs, DeFi, tokens, mining, wallets, and crypto investing or trading.",
    "personal_finance": "Budgeting, saving, debt, taxes, retirement planning, FIRE, banking, insurance, credit cards, mortgages, home buying, rent-versus-buy decisions, real estate purchases for personal use, and household financial decisions.",
    "economics": "Economics, macroeconomics, economic policy, business strategy, entrepreneurship, industries, firms, labor markets, and business or economic news.",
    "politics_news": "Politics, government, elections, public policy, political ideology, current events, and news.",
    "technology": "Programming, software, hardware, artificial intelligence, cybersecurity, consumer technology, operating systems, engineering, and software tools.",
    "science": "Academic research, natural sciences, medicine as a scientific discipline, mathematics, physics, chemistry, biology, and scientific discussion.",
    "gaming": "Video games, tabletop games, game-specific communities, esports, game development, and gaming culture.",
    "sports": "Sports teams, athletes, leagues, competitions, sporting events, and sports discussion.",
    "health_and_fitness": "Exercise, fitness, nutrition, physical health, healthy lifestyles, sports training, recovery from physical injury, and general wellness.",
    "mental_health_support": "Mental health support, emotional wellbeing, therapy, anxiety, depression, ADHD, trauma, addiction recovery, crisis support, peer support, and communities focused on coping with psychological distress.",
    "automotive_and_transportation": "Cars, motorcycles, trucks, aviation, trains, bicycles, public transport, vehicle ownership, and transportation. Excludes firearms, guns, shooting, and weapons communities, which belong in other_hobbies unless another category clearly fits better.",
    "other_hobbies": "Recreational hobbies and enthusiast communities including DIY, woodworking, crafts, model building, collecting, outdoor recreation, musical instruments, firearms, guns, shooting sports, weapons collecting, and other leisure activities.",
    "art_design_and_photography": "Visual arts, illustration, graphic design, photography, architecture, drawing, painting, and creative design.",
    "food_and_drink": "Cooking, recipes, baking, restaurants, beverages, coffee, tea, food culture, and culinary discussion.",
    "lifestyle_and_fashion": "Fashion, beauty, skincare, grooming, interior lifestyle, personal style, and aesthetics.",
    "travel": "Travel, tourism, destinations, trip planning, digital nomads, and travel advice.",
    "productivity_and_career": "Jobs, careers, resumes, interviews, workplace issues, studying for careers, professional development, certifications, productivity, and time management.",
    "relationships_and_family": "Dating, marriage, parenting, friendships, family relationships, and interpersonal relationships.",
    "spirituality_and_philosophy": "Religion, spirituality, philosophy, ethics, belief systems, and existential discussion.",
    "gambling": "Sports betting, casinos, poker, lotteries, betting strategies, and gambling communities.",
    "media_entertainment": "Movies, television, music, anime, books, comics, podcasts, celebrities, and entertainment media.",
    "humor_and_memes": "Memes, jokes, satire, comedy, humorous images, shitposting, and parody communities.",
    "education": "Schools, universities, learning resources, studying, teaching, academic life, and educational discussion.",
    "nature_and_animals": "Pets, animals, wildlife, gardening, plants, environmental topics, and nature.",
    "home_and_housing": "Housing and home-related communities, including renting, apartments, roommates, home improvement, DIY renovation, appliances, interior design, and everyday housing issues not primarily focused on financial decisions or investment returns.",
    "law_and_legal": "Law, legal advice, courts, legal professions, law school, and legal discussion.",
    "nsfw_and_porn": "Adult content, pornography, explicit sexual content, and NSFW communities.",
    "places_and_geographies": "Countries, cities, regions, local communities, languages, and location-based subreddits.",
    "general_advice_and_discussion": "General discussion, question-and-answer communities, AskReddit-style forums, advice, AMAs, support, and broad conversation.",
    "other_unknown": "Cannot be confidently assigned to any substantive category.",
}

STAGE2_TAXONOMY = {
    "general_investing_and_implementation": {
        "title": "General investing and implementation",
        "core_purpose": "Broad participation in equity markets and the practical implementation of investing.",
        "typical_content": "Diversification, ETFs, mutual funds, valuation, dividends, portfolio allocation, retirement investing, broker choice, account opening, transfers and account rules.",
    },
    "active_trading_and_derivatives": {
        "title": "Active trading and derivatives",
        "core_purpose": "Short-horizon trading and tactical position management.",
        "typical_content": "Day trading, swing trading, technical analysis, options, futures, leverage, order execution and trading strategies.",
    },
    "single_securities_and_investment_themes": {
        "title": "Single securities and investment themes",
        "core_purpose": "Discussion organized around a particular company, security, sector or product theme.",
        "typical_content": "Tesla, Nvidia, Palantir, cannabis stocks, space stocks, REIT themes, dividend ETFs, specific fund families.",
    },
    "meme_squeeze_and_highly_speculative_communities": {
        "title": "Meme, squeeze and highly speculative communities",
        "core_purpose": "Collective speculation, viral narratives and event-driven trading.",
        "typical_content": "WSB-style discussion, GME/AMC communities, short squeezes, penny-stock promotion, ‘apes,’ YOLO trades and coordinated speculative narratives.",
    },
}
