"""The fixed, mutually exclusive stage-1 taxonomy."""
TAXONOMY = {
    "stock_market": "Discussion primarily about publicly traded stocks, equity markets, trading, or market-wide investing.",
    "personal_finance": "Managing personal money, budgeting, saving, debt, insurance, or financial planning.",
    "crypto": "Cryptocurrencies, blockchain tokens, decentralized finance, or digital assets.",
    "real_estate": "Buying, selling, renting, financing, or investing in real property.",
    "economics": "Macroeconomics, economic policy, indicators, trade, or economic theory.",
    "business": "Companies, entrepreneurship, management, startups, and general business strategy.",
    "careers": "Jobs, workplaces, careers, professional development, or employment advice.",
    "technology": "Computers, software, programming, hardware, and general technology.",
    "science": "Natural, formal, or social science and scientific research.",
    "education": "Schools, universities, teaching, studying, and education systems.",
    "politics": "Government, elections, public policy, political parties, or political debate.",
    "news": "Reporting, discussion, or analysis of current events and journalism.",
    "law": "Legal questions, courts, legislation, regulation, or legal practice.",
    "health": "Physical health, medicine, healthcare, or medical conditions.",
    "mental_health": "Mental health, therapy, psychological wellbeing, or psychiatric conditions.",
    "fitness": "Exercise, training, sports conditioning, or physical performance.",
    "food_and_drink": "Cooking, recipes, restaurants, food, beverages, and eating.",
    "travel": "Trips, destinations, tourism, transportation, and travel planning.",
    "gaming": "Video games, tabletop games, esports, or gaming culture.",
    "sports": "Organized sports, athletes, teams, leagues, and sporting events.",
    "music": "Music, musicians, instruments, performances, and music production.",
    "movies_tv": "Films, television, streaming shows, and screen entertainment.",
    "books_writing": "Books, literature, authors, reading, and creative writing.",
    "arts_crafts": "Visual arts, crafts, making, design, and creative projects.",
    "fashion_beauty": "Clothing, style, cosmetics, grooming, and beauty.",
    "relationships": "Romantic, family, friendship, and interpersonal relationships.",
    "parenting": "Pregnancy, children, parenting, and family child-rearing.",
    "animals_pets": "Pets, animal care, wildlife, and animal interests.",
    "hobbies": "A focused leisure interest not better covered by another category.",
    "humor": "Jokes, memes, satire, and primarily humorous content.",
    "religion_spirituality": "Religion, faith, spirituality, and religious practice.",
    "other": "A substantial topic that does not fit any category above; use sparingly.",
}
